name: pb_controller
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+9

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.0.2
  shared_preferences: ^2.5.3
  permission_handler: ^11.3.1
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  device_info_plus: ^12.2.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

  build_runner: ^2.10.4
  freezed: ^3.1.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/Logo/
    - assets/icons/botton/

flutter_native_splash:
  android: true
  ios: true
  color: "#050910"
  color_dark: "#050910"
  image: assets/Logo/Splash_Screen.png
  image_dark: assets/Logo/Splash_Screen.png

  android_12:
    color: "#050910"
    color_dark: "#050910"
    image: assets/Logo/Splash_Screen.png
    image_dark: assets/Logo/Splash_Screen.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo/App_Icon.png"
  adaptive_icon_foreground: "assets/Logo/App_Icon.png"
  adaptive_icon_background: "#121212"

